# Get all directors

GET http://localhost:9080/jeelab/api/directors

###

# Get single director

GET http://localhost:9080/jeelab/api/directors/11111111-1111-1111-1111-d117867118e3

###

# Get single director not existing

GET http://localhost:9080/jeelab/api/directors/6d6f1eb1-1234-2345-1234-d7fed2b65d87

###

# Get director movies

GET http://localhost:9080/jeelab/api/directors/11111111-1111-1111-1111-d117867118e3/movies

###

# Get all movies

GET http://localhost:9080/jeelab/api/movies

###

# Get single movie

GET http://localhost:9080/jeelab/api/movies/7d1da2ae-1234-2345-1234-d117867118e3

###

# Get single movie not existing

GET http://localhost:9080/jeelab/api/directors/6d6f1eb1-1234-2345-1234-d7fed2b65d87

###

# Create new director.

PUT http://localhost:9080/jeelab/api/directors/6d6f1eb1-1234-2345-1234-d7fed2b65d87
Content-Type: application/json

{
  "birthDate": "2001-10-15",
  "name": "Nowy",
  "oscarAwards": 10,
  "surname": "Rezyser"
}

###

# Get new director

GET http://localhost:9080/jeelab/api/directors/6d6f1eb1-1234-2345-1234-d7fed2b65d87

###

# Get all directors

GET http://localhost:9080/jeelab/api/directors

###

# Create new movie.

PUT http://localhost:9080/jeelab/api/movies/1a1f1eb1-2345-2345-2345-d117867118e3
Content-Type: application/json

{
  "directorId": "11111111-1111-1111-1111-d117867118e3",
  "releaseDate": "2024-10-26",
  "runningTime": 111,
  "title": "New movie"
}

###

# Get new movie

GET http://localhost:9080/jeelab/api/movies/1a1f1eb1-2345-2345-2345-d117867118e3

###

# Get all movies

GET http://localhost:9080/jeelab/api/movies

###

# Update director

PATCH http://localhost:9080/jeelab/api/directors/11111111-1111-1111-1111-d117867118e3
Content-Type: application/json

{
  "name": "New Peter",
  "surname": "New Jackson",
  "oscarAwards": 3,
  "birthDate": "1961-10-31"
}

###

# Get updated director

GET http://localhost:9080/jeelab/api/directors/11111111-1111-1111-1111-d117867118e3

###

# Update movie

PATCH http://localhost:9080/jeelab/api/movies/7d1da2ae-1234-2345-1234-d117867118e3
Content-Type: application/json

{
  "releaseDate": "2003-12-17",
  "runningTime": 201,
  "title": "New The Lord of the Rings: Return of the King"
}

###

# Get updated movie

GET http://localhost:9080/jeelab/api/movies/7d1da2ae-1234-2345-1234-d117867118e3

###

# Delete director

DELETE http://localhost:9080/jeelab/api/directors/11111111-1111-1111-1111-d117867118e3

###

# Get all directors

GET http://localhost:9080/jeelab/api/directors

###

# Get all movies

GET http://localhost:9080/jeelab/api/movies

###

# Delete movie

DELETE http://localhost:9080/jeelab/api/movies/1d1da2a4-1122-3344-5566-d117867118e3

###

# Get all movies

GET http://localhost:9080/jeelab/api/movies

###